### ISSUE TITLE
Pull request link doesn't match when triggering repository dispatch

### ISSUE THREAD

**Issue by kalebsembiring** [peter-evans/repository-dispatch#112]
Hi @peter-evans, currently i have a workflow that triggers repository dispatch from issue comments. This has been an issue since the the repository dispatch workflow doesn't displayed the current PR when triggering from issue comments job. Is there any chance to hardcode the PR to be displayed for repository dispatch? Thank You!

Repository Dispatch :
<img width="585" alt="Screen Shot 2022-05-13 at 10 56 03" src="https://user-images.githubusercontent.com/90230528/168208220-afda6aba-b1cc-4e1c-970f-dc38a1bfc006.png">

Issue Comments :
<img width="332" alt="Screen Shot 2022-05-13 at 10 58 09" src="https://user-images.githubusercontent.com/90230528/168208519-be128faa-e4c4-4734-928a-ff3d5dccf3fb.png">

**Comment by peter-evans** [comment]
Hi @kalebsembiring 

Sorry, I don't really understand what you are trying to do. Any information that you need must be passed in the `payload`. The action doesn't know anything about specifics of use cases, like PR numbers.

I'm going to close this because I think this is more about using the action than an issue with the action itself.
