### ISSUE TITLE
Using latest 2.1.2 - workflow triggers twice.

### ISSUE THREAD

**Issue by LaithDaman** [peter-evans/repository-dispatch#272]
Hello, this is my first time using this 'peter-evans/repository-dispatch' based on following examples (see links below). 

When I tried this 'peter-evans/repository-dispatch', I noticed the workflow is triggered twice: 
One with 'Reusale Workflow' and another one with my name. The 'Reusale' one gets stuck but the other one finishes. See attached file for "Output", "File 1" - caller, and "file 2" callee.

I can appreciate the help or root cause for this problem, or what am I missing. 
Both repos are on private network and valid secrets.pat works 100%.

Links:
Following: https://stevenmortimer.com/running-github-actions-sequentially/
Example:   https://github.com/StevenMMortimer/salesforcer/tree/main/.github/workflows
API:       https://github.com/marketplace/actions/repository-dispatch 
Other example
(1) https://cloud-native.devsecopsgirl.in/deployment/

[issue_peter_evans_repository_dispatch.txt](https://github.com/peter-evans/repository-dispatch/files/12842528/issue_peter_evans_repository_dispatch.txt)

**Comment by peter-evans** [comment]
Hi @LaithDaman 

I had a look at the attached text file. It looks like you are using self-hosted Actions runners, so that might be related to the problem. Please check that the runners are setup correctly and they can reach GitHub's API. It might be a good idea to test your setup with hosted runners first, to check it works before trying to use your own runners.

I don't see anything obvious as to why it would trigger twice.

**Comment by LaithDaman** [comment]
Hi @peter-evans 
Thank you for the quick response. The self-hosted work 100% and manually tested using the 'workflow_dispatch'. 

I removed it from yml file since as I wanted a single point of entry (this may have been the root cause for triggered twice). 

I applied your suggestions: I used 'ubuntu-latest' for both yml files (caller and callee).
The twice triggering is not longer there. But the issue still remains about callee workflow hangs.

```
Requested labels: EC2AMAZ-EVN2U58
Job defined at: _company_/EarthSlide/.github/workflows/reusable_workflow.yml@refs/heads/master
Waiting for a runner to pick up this job...
```

**Comment by peter-evans** [comment]
Sounds like the double triggering is fixed. 👍 

> Waiting for a runner to pick up this job...

This is nothing to do with this action. This is suggesting that it's waiting for a runner to pick up the job. It's an issue to do with self-hosting.

**Comment by LaithDaman** [comment]
As I mentioned, the new code is not using self-hosting. Both files changed from Self-Hosting to 'Ubuntu-latest' as you have suggested. Maybe I did not clearly understand what you mean then.

`runs-on: ubuntu-latest #  [ EARTHSLIDE_LAITHD_LOCAL ]`

**Comment by peter-evans** [comment]
> Do I take it that 'peter-evans/repository-dispatch' does not work or is not tested on self-hosted machines?

No, I think it should run on self-hosted machines just fine. There are thousands of users using this action and I would be very surprised if none of them are using self-hosted.

My point was, if you are seeing this message `Waiting for a runner to pick up this job..` it means that GitHub actions is waiting for a self-hosted machine to pick up the job. So perhaps you didn't properly switch to GitHub hosted for your test. This message has absolutely nothing to do with this action, it's generated by GitHub's platform because it can't find a runner to execute the job.

**Comment by LaithDaman** [comment]
I figured out what was wrong, another yml file workflow had "repository_dispatch:" without any guard condition. Hence it was triggering two workflows (with guard condition as expected and without).

It works flawlessly now. Thank you.
Regards
