### ISSUE TITLE
Incorrect Usage in README.md

### ISSUE THREAD

**Issue by paullaffitte** [peter-evans/repository-dispatch#32]
The usage specify:

```
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
```

But the version `v1` doesn't exists. It should be `v1.0.0` or `v1.1.1` to use the current latest version.

**Comment by peter-evans** [comment]
Hi @paullaffitte 

The documentation is correct. `v1` is actually a branch, not a tag. GitHub actions versioning works for both tags and branches and their original recommendation was to release major versions as a branch. I think they might have changed that advice relatively recently because I see many of the official GitHub actions using major version tags now. There is not really any difference between either method, though.

https://github.com/peter-evans/repository-dispatch/tree/v1
