### ISSUE TITLE
Workflow intermittently triggers the dispatch target twice

### ISSUE THREAD

**Issue by bbimber** [peter-evans/repository-dispatch#360]
Hello,

Thanks for this very useful action. Broadly speaking this is working perfectly, but some of the time, and I cannot really see a pattern, it double-triggers the action on the target repo. This is the source repo's yml file:

https://github.com/bimberlabinternal/docker-base/blob/1d83e0aca63fb5abb85999d41a39aa1461df89eb/.github/workflows/docker.yml#L59

You'll see it triggers a docker workflow on several target repos. One example is this:

https://github.com/BimberLab/cellhashR/blob/8bcfc631818f7496fe9a620d1c5165c9f40897de/.github/workflows/docker.yml#L7

Again, the vast majority of the time this works perfectly, but some of the time it results in double-triggering of the target. This is a complete guess, but could this be something like the plugin making an HTTP request to trigger the workflow, that requesting timing out or erroring, and then the plugin repeats the request?  

In our case, the target is just building a docker image so the impact is not huge, but I thought I would report this. I'm happy to try some debugging if anything would help.

**Comment by peter-evans** [comment]
Hi @bbimber 

I don't think the action retries failed requests. What I think is more likely is that GitHub's internal systems are retrying the delivery of the dispatch due to transient failures. My guess would be that the system is designed to delivery with "at-least-once" semantics, so occasional double-triggers are somewhat unavoidable.

What you could do is send a unique key with the dispatch and check it in the target workflow to make sure you only execute once.

**Comment by bbimber** [comment]
OK, thanks for the suggestions
