### ISSUE TITLE
workflow triggered by wrong actor

### ISSUE THREAD

**Issue by TJKrawczynski2** [peter-evans/repository-dispatch#40]
I love this action, it made starting workflows from other repositories super easy. We are using this action in a submodule repository to trigger workflows on all repositories which use the submodule whenever master is updated. 

The problem we are finding is that workflow runs triggered by repository-dispatch are reporting "Repository dispatch triggered by TJKrawczynski2" in the actions tab always, even when the original repository-dispatch action was triggered by someone else in the submodule. Essentially this means TJKrawczynski2 (me) is the only one who gets notified of failed CI runs instead of the developers who originally made changes on the submodule.

I suspect the "actor" field is not getting forwarded to the repository_dispatch-triggered workflow properly, I tried looking over your code but got a little lost since I've never worked with typescript or any java-related languages really... Any help will  be appreciated!

**Comment by peter-evans** [comment]
@TJKrawczynski2 The `actor` of the `repository_dispatch` workflow will always be the user account associated with the token you are using. Instead of using your own account to create the token, what I would suggest is to make a new GitHub account as a "machine account." Make sure the account has access to the target repositories and create the `repo` scoped token for use with this action. Additionally, set an email address for the machine account that acts as an email group. So emails to that address will be delivered to all members of your team. Then when the CI run fails, your whole team should be notified.

**Comment by TJKrawczynski2** [comment]
@peter-evans Oh. I see, that's good to know. That is good advice, a targeted email would be a little nicer but I like your solution. Thanks!

**Comment by peter-evans** [comment]
> a targeted email would be a little nicer

Not sure what you mean by this. My suggestion of a group email was because I think you can only set one email address in GitHub's account settings to receive notifications.

Unfortunately, I can't do anything in this action to help you. What you are experiencing is tied to the way user accounts, notifications, and authentication work on GitHub. I think the solution I outlined above will be the best option for you.
