### ISSUE TITLE
Improve the error message when the token has insufficient permissions

### ISSUE THREAD

**Issue by akhmerov** [peter-evans/repository-dispatch#50]
I ran into the same problem reported in #34, where the error with the workflow just reported "not found", without providing any information wrt what is not found. Reading the issue discussion helped, however I suggest to make the error message more informative.

**Comment by peter-evans** [comment]
Hi @akhmerov 

Unfortunately, I don't think it's possible for the action to know exactly what the issue is. That is because the GitHub API returns `404 Not Found` when the token doesn't have sufficient permissions, and when it does have sufficient permissions but the target repository URL is incorrect. I think this is by design to prevent leaking information about private repositories.

What I could do, though, is add a message which explains it could be either of the two cases I mentioned above.

**Comment by akhmerov** [comment]
It would be possible to separately detect if the bot user can find the repository but not trigger dispatch by performing another query.

However adding a message listing possible failure modes would fully address the problem, great idea!

**Comment by peter-evans** [comment]
Improved the error message in the latest release.
