### ISSUE TITLE
Prevent potential token log

### ISSUE THREAD

**Issue by arothian** [peter-evans/repository-dispatch#58]
While Github Actions will try to redact secrets printed to logs, I think it would be best if the debug logging in this action didn't include the GH token configured.

https://github.com/peter-evans/repository-dispatch/blob/master/src/main.ts#L13

https://docs.github.com/en/actions/reference/encrypted-secrets
>Warning: GitHub automatically redacts secrets printed to the log, but you should avoid printing secrets to the log intentionally.

**Comment by peter-evans** [comment]
Hi @arothian 

Thanks for pointing this out but I'm not too concerned about this because by default the GitHub Actions runner doesn't print debug lines anyway. You have to explicitly enable it by setting the secret `ACTIONS_STEP_DEBUG` to `true` in the repository where the workflow is running. Anyone who is extra cautious can just not enable that debug output.
