### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by davidkarlsen** [peter-evans/repository-dispatch#77]
note that you no longer need to leak a PAT in order to do dispatch, as you can add the `actions: write` permission to the workflow to elevate the scope.

* https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
* https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idpermissions

**Comment by davidkarlsen** [comment]
Sorry, I was wrong, it will return `204 created` with this scope, but the wf won't actually trigger.

**Comment by peter-evans** [comment]
Hi @davidkarlsen 

The blog update on the 20th April I believe only allows you to reduce the scopes present in the current token. It doesn't allow you elevate the scopes further, as far as I'm aware. So in the case of repository dispatch, you still need to use a PAT because that scope is not included in the default token.
